<main>
    <nav class="side counter">
        <?php if($page > 1): ?>
            <a class="stream" href="?page=<?= $page - 1 ?>"><i class="fas fa-chevron-left"></i> Précédent</a>
            <a href="?page=<?= 1 ?>"><?= 1 ?></a>
            <?php if($page < 9): ?>
                ...
            <?php endif ?>
        <?php endif ?>
        <?php if($page >= 9): ?>
            <a href="?page=<?= ceil($page / 3) ?>"><?= ceil($page / 3) ?></a>
            <a href="?page=<?= ceil($page * 2 / 3) ?>"><?= ceil($page * 2 / 3) ?></a>
            ...
        <?php endif ?>
        <?php if($page >= 3): ?>
            <?php for($i = $page - 2; $i < $page; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if($nbPages > 1): ?>
            <a class="current" href="?page=<?= $page ?>"><?= $page ?></a>
        <?php endif ?>
        <?php if($page <= $nbPages - 2): ?>
            <?php for($i = $page + 1; $i <= $page + 2; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) >= 3): ?>
            ...
            <a href="?page=<?= ceil(1/3 * ($nbPages - $page) + $page) ?>"><?= ceil(1/3 * ($nbPages - $page) + $page) ?></a>
            <a href="?page=<?= ceil(2/3 * ($nbPages - $page) + $page) ?>"><?= ceil(2/3 * ($nbPages - $page) + $page) ?></a>
        <?php endif ?>
        <?php if($page < $nbPages): ?>
            <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) < 3): ?>
                ...
            <?php endif ?>
            <a href="?page=<?= $nbPages ?>"><?= $nbPages ?></a>
            <a class="stream" href="?page=<?= $page + 1 ?>">Suivant <i class="fas fa-chevron-right"></i></a>
        <?php endif ?>
    </nav>
    <?php if($nbPictures > 0): ?>
        <noscript>
            <p>
                Pour accéder à cette fonctionnalité, vous devez activer JavaScript. Voici les
                <a href="https://www.enable-javascript.com/fr/">instructions pour activer JavaScript dans votre navigateur Web</a>.
            </p>
        </noscript>
        <?php for($i = ($page - 1) * $limit + 1; $i <= $page * $limit; $i++): ?>
            <figure class="blog">
                <embed class="rig" src="<?= $dirPicture . $i ?>.pdf">
                <figcaption>
                    <?php $comment = @file_get_contents($dirComment . $i . '.txt') ?>
                    <p class="commentblog"><?= $comment ?></p>
                </figcaption>
            </figure>
        <?php endfor ?>
    <?php else: ?>
        <p id="nothing">Ce blog ne contient pas de dessin.</p>
    <?php endif ?>
    <nav class="side counter">
        <?php if($page > 1): ?>
            <a class="stream" href="?page=<?= $page - 1 ?>"><i class="fas fa-chevron-left"></i> Précédent</a>
            <a href="?page=<?= 1 ?>"><?= 1 ?></a>
            <?php if($page < 9): ?>
                ...
            <?php endif ?>
        <?php endif ?>
        <?php if($page >= 9): ?>
            <a href="?page=<?= ceil($page / 3) ?>"><?= ceil($page / 3) ?></a>
            <a href="?page=<?= ceil($page * 2 / 3) ?>"><?= ceil($page * 2 / 3) ?></a>
            ...
        <?php endif ?>
        <?php if($page >= 3): ?>
            <?php for($i = $page - 2; $i < $page; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if($nbPages > 1): ?>
            <a class="current" href="?page=<?= $page ?>"><?= $page ?></a>
        <?php endif ?>
        <?php if($page <= $nbPages - 2): ?>
            <?php for($i = $page + 1; $i <= $page + 2; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) >= 3): ?>
            ...
            <a href="?page=<?= ceil(1/3 * ($nbPages - $page) + $page) ?>"><?= ceil(1/3 * ($nbPages - $page) + $page) ?></a>
            <a href="?page=<?= ceil(2/3 * ($nbPages - $page) + $page) ?>"><?= ceil(2/3 * ($nbPages - $page) + $page) ?></a>
        <?php endif ?>
        <?php if($page < $nbPages): ?>
            <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) < 3): ?>
                ...
            <?php endif ?>
            <a href="?page=<?= $nbPages ?>"><?= $nbPages ?></a>
            <a class="stream" href="?page=<?= $page + 1 ?>">Suivant <i class="fas fa-chevron-right"></i></a>
        <?php endif ?>
    </nav>
</main>