<main>
    <h3>Le dessin et moi</h3>
    <p>
        Comment cette aventure a-t-elle commencé pour moi&nbsp;?
        Depuis l'école maternelle, je n'avais jamais pris le temps de m'y intéresser.
        Les filles dessinent entre elles et progressent plus vite que moi.
        <strong>Je vois alors les peintures sur toile qu'elles font à l'âge de dix ans&nbsp;!</strong>
    </p>
    <p>
        J'exagère un peu, mais je me dis que le dessin, c'est totalement hors d'atteinte des garçons.
        La plupart des filles qui me lisent voient malheureusement bien de quoi je parle.
        Et j'ai fini par sacraliser la chose en voyant dessiner d'autres plus expérimentés que moi.
    </p>
    <p>
        <strong>Le premier travail que j'ai fait sur moi a été de désacraliser le dessin</strong>.
    </p>
    <p>
        <strong>Comment j'ai fait&nbsp;?</strong> En observant une étudiante qui était dans mon groupe à l'université,
        elle dessinait tout le temps. Typiquement le genre de situation dans laquelle je me dis&nbsp;:
        <q>&nbsp;Houlà, les génies avec leurs dessins, laissons-les tranquilles dans leur petit monde&nbsp;!&nbsp;</q>.
        Mais chaque jour pendant des années, je la voyais dessiner à la même table.
        Chaque jour pendant des années, j'avais la réponse à la question&nbsp;: <q>&nbsp;Mais comment elle fait&nbsp;?&nbsp;</q>.
        Réponse&nbsp;: <q>&nbsp;<strong>Elle en a fait hier</strong>&nbsp;</q>.
        Le dessin, c'est magique, mais <strong>c'est le fruit d'un travail</strong>. Pas d'abracadabra&nbsp;!
    </p>
    <p>
        Alors je m'y suis mis. Qu'est-ce qu'il me faut pour que je fournisse le même travail,
        et donc que je parvienne aux mêmes résultats&nbsp;? <strong>Une méthode</strong>. Ne connaissant rien au dessin,
        je me suis procuré les manuels didactiques fournissant la formule qui m'était la plus adaptée.
        Vous devrez vous aussi trouver la vôtre. Une recommandation, les mots-clés "apprendre" et "dessiner" sur Amazon.
        Rien de bie sorcier ! Vous recoupez ensuite les thèmes de manière à avoir un <strong>apprentissage graduel</strong>.
    </p>
    <p>
        Dans mon cas, comme le verrez dans le blog, je suis parti <strong>des formes simples</strong>, vers <strong>les silhouettes</strong>,
        puis <strong>les personnages</strong>, <strong>les parties du corps</strong> en détail.
        Viendront <strong>les vêtements</strong>, <strong>le mouvement</strong>, <strong>l'action</strong>, <strong>les décors</strong>, etc.
    </p>
    <p>
        <strong>La réévaluation des compétences est constante et omniprésente</strong>.
        Parfois, je suis sûr de réussir un dessin et je me rends compte que je n'ai pas les moyens de le réussir.
        Parfois, je me dis que tel autre ne pourra se faire que dans des années et des années et je le dessine
        au bout de quelques semaines&nbsp;! <strong>Le chemin évolue en permanence</strong>.
    </p>
    <p>
        Je me suis mis aux mangas, également. Les <em>anime</em> qui passent à la télévision n'en sont pas représentatifs.
        C'est comme si vous vous faisiez une idée du cinéma en ne regardant que des feuilletons.
        Je suis attentif <strong>aux histoires</strong> et, bien sûr, <strong>au dessin</strong>.
    </p>
    <p>
        <strong>Vous évoluerez. À votre rythme. Très rapidement, vous dessinerez non parce que vous voulez réussir des choses,
        mais parce que vous savez les faire. Parce que que vous aurez les moyens de créer vos histoires.</strong>
    </p>
    <p>
        Alors, on s'y met&nbsp;?
    </p>
</main>