<main>
    <h1>Prends ton dessin en main&nbsp;!</h1>
    <h5>Du tout en un qui ne te salit pas les mains&nbsp;!</h5>
    <p><strong>Bienvenue sur mon blog&nbsp;!</strong></p>
    <p>
        La première chose que vous vous dites, et que vous devez vous dire, c'est&nbsp;: <strong>pourquoi mon blog&nbsp;?</strong>
        En effet, quand on se met au dessin, quand on est piqué de curiosité (et ça commence comme ça&nbsp;!)
        ou qu'on a la plus petite émulation vis-à-vis d'une œuvre ou une personne qui nous inspire,
        on se souvient d'un vieil ami qui ne nous juge jamais&nbsp;: <strong>Google&nbsp;!</strong>
    </p>
    <p>
        <strong>Alors on recherche</strong> "dessin" ou "conseil dessin" sur Google. Bing pour quelques-uns, mais vous m'avez compris.
        Je n'oublie pas non plus ces trop peu nombreux moteurs de recherche écolo.
        Bref, c'est un premier pas, et croyez-moi, c'est le plus important. Les blogs ne manquent pas.
        Les conseils ne manquent pas. D'autres sont là pour nous aider.
    </p>
    <p>
        <strong>Et là on est très vite perdu</strong>.
        Les informations arrivent comme on les attend, mais ça ne nous dit pas par où commencer.
        Bien souvent, on vous dit comment ne pas finir quand vous cherchez comment commencer.
    </p>
    <p>
        <strong>Et c'est là que ça devient intéressant</strong>&nbsp;:
        qu'en sait l'autre de comment vous fonctionnez, de ce dont vous avez besoin, de ce que vous recherchez&nbsp;?
        D'autant que s'appuyer sur les autres, c'est nécessaire mais ça pose un problème&nbsp;:
        <strong>on ne se regarde pas soi-même</strong>.
    </p>
    <p>
        Commencer à dessiner, c'est prendre conscience d'un potentiel personnel.
        Si vous avez ne serait-ce qu'un murmure qui vous souffle dans l'oreille <q>&nbsp;<strong>Et si le dessin, c'était pour moi&nbsp;?</strong>&nbsp;</q>,
        c'est que vous avez ce potentiel. Vous en prendrez conscience par la pratique.
        Donc, tant que vous ne vous y mettez pas,
        vous n'en aurez jamais conscience et vous n'aurez pas cette dynamique de <q>&nbsp;<strong>C'est moi qui tiens les rênes</strong>&nbsp;</q>.
    </p>
    <p>
        <strong>La raison d'être de ce blog</strong> est de vous offrir les outils humains et numériques qui vous permettront de vous amuser en dessin
        (ce qu'on fait trop peu souvent) et de vous découvrir. Pas découvrir un talent jusqu'alors en stase,
        <strong>vous découvrir vous à travers le travail</strong>.
    </p>
    <p>
        Car c'est ainsi que ça commence.
        <strong>Si Michel-Ange a pu y arriver, vous le pouvez et c'est aussi simple que ça</strong>.
        Sauf cas exceptionnel, ce n'est que le travail qui permet le dessin.
        Bien sûr, il y a la question des affinités, mais nous faisons tous ce que nous pouvons avec ce que nous avons.
        Et puis <q>&nbsp;<strong>les grandes choses ont de petits commencements</strong>&nbsp;</q>, dixit l'androïde Fassbender&nbsp;!
    </p>
    <p>
        Mais quand bien même vous aurez cette citation en tête, rien ne peut vous préparer à l'aventure qui vous attend.
    </p>
    <p>
        <strong>Le dessin va devenir pour vous une seconde nature</strong>.
        Quand je parle de discipline, je n'entends pas de l'acharnement, des privations, ou des moments de solitude.
        Vous allez rapidement développer vos propres méthodes, vous auto-alimenter en bonnes idées,
        <strong>vous allez observer le monde qui vous entoure</strong>.
        En terme de ressources, le dessin vous apportera beaucoup plus qu'il ne vous coûtera.
        Bien sûr, vous avancerez calmement et pas à pas, et vous constaterez deux choses en lesquelles vous n'avez pas cru&nbsp;:
    </p>
    <ol>
        <li>
            &#8594;	<strong>Vous comprendrez vos progrès devant le dessin dès lors qu'il aura été fait</strong>, et ce quel qu'il soit.
        </li>
        <li>
            &#8594; Vous pensez revenir à lui dans quelques mois, quelques années, et vous dire&nbsp;:
            <q>&nbsp;Quelle horreur&nbsp;! Ce que j'étais mauvais à l'époque&nbsp;!&nbsp;</q>&nbsp;? <strong>Non</strong>.
            Ce sera tout aussi extatique lorsque vous y reviendrez,
            car il vous apprendra énormément sur votre parcours et vous vous demanderez avec le recul
            <strong>comment vous avez pu réaliser une œuvre complète avec aussi peu</strong>.
        </li>
    </ol>
    <p>
        Je parle de blog mais ce site est beaucoup plus qu'un blog. Le blog en lui-même <strong>présente mes dessins</strong>&nbsp;:
        tout ce que que j'ai jamais dessiné à ce jour et j'ai déjà de quoi partage et en inspirer d'autres&nbsp;!
        Je les commente pour illustrer les deux points ci-dessus&nbsp;:
        mes impressions en temps réelle et ce que je vois et apprends de lui avec mon regard d'aujourd'hui.
        L'idée de base&nbsp;: tout dire, tout révéler. Car tout est important. Et surtout, <strong>tout est beau</strong>.
    </p>
    <p>
        Par la suite, si vous avez la phobie du crayon, vous avez carte blanche, et c'est ce cas de le dire,
        avec <strong>l'ardoise numérique</strong> qui vous permettra (écran tactile recommandé&nbsp;!) de vous faire un peu les crocs.
        Et vous pourrez <strong>discuter de tout ceci avec le forum</strong>.
        Ce forum orienté débutant vous incitera à ne pas taire vos échecs et ne pas vous sentir écrasé par les "faux modestes malgré eux" qui ont un <em>pedigree</em> de luxe&nbsp;!
    </p>
    <p>
        Pour finir, <strong>enregistrez-vous et vous en aurez plus&nbsp;!</strong>
        Vous pourrez importer vos propres dessins et retrouver toutes vos créations dans votre espace <em>Dessins</em>.
        Vous deviendrez également membre à part entière du forum.
        Vous en aiderez d'autres et d'autres vous aideront. Vous leur donnerez notamment accès à <strong>vos dessins publics</strong> et inversement.
    </p>
    <p>
        N'oubliez pas&nbsp;: le dessin, et c'est là la source de tout acte de création, <strong>doit sortir de vos tripes</strong>.
        Bien vous entourer est un luxe très appréciable, notamment si vous doutez d'une bonne ligne directrice
        (je vous montrerai tout du moins mon parcours), mais ça ne comptera pas pour ce qui est de garder un cap au long terme.
        Pour çela, vous serez seul et c'est dès maintenant que vous en prenez conscience.
    </p>
    <p>
        J'ai dit que je vous enseignerai les bases&nbsp;? Avec quelques dizaines de dessins à mon actif&nbsp;??
        Oui, mais alors là il y a paradoxe&nbsp;: ce blog va-t-il vraiment vous tirer vers le haut&nbsp;?
        Réponse&nbsp;: <strong>il va vous pousser vers le haut&nbsp;!</strong>
        Jusqu'à un certain point. Il n'est pas conçu pour vous guider sur le cap à long terme.
        S'il peut contribuer à faire de vous le dessinateur que vous voulez être, c'est déjà superbe.
        Et puis, son objectif est bien de dire que <em><strong>tout le monde peut cuisiner&nbsp;!</strong></em> Heu, dessiner.
    </p>
    <p>
        À ce propos, voici <a id="aboutme" href="<?= $app ?>aboutme.php">comment ça a commencé pour moi.</a>
    </p>
</main>