<main>
    <h2>Mot de passe oublié</h2>
    <form class="form" action="<?php $mail ?>" method="post">
        <fieldset>
            <legend>Envoi de mot de passe</legend>
            <label for="loginMail">Votre pseudo ou adresse e-mail :</label>
            <input type="text" id="loginMail" name="loginMail">
        </fieldset>
        <input type="submit" name="submit" value="Recevoir mon nouveau mot de passe">
    </form>
</main>