<main>
    <form class="form" action="<?php $file ?>" method="post">
        <fieldset>
            <legend>Chercher les dessins publics d'un utilisateur</legend>
            <ul>
                <li>
                    <label for="user">Dessins de :</label>
                    <input type="text" id="user" class="empty" name="user">
                </li>
            </ul>
        </fieldset>
        <input type="submit" name="submit" value="Trouver les dessins">
    </form>
</main>