<main>
    <nav class="counter">
        <?php if($page > 1): ?>
            <a class="stream" href="?id=<?= $idUser ?>&page=<?= $page - 1 ?>"><i class="fas fa-chevron-left"></i> Précédent</a>
            <a href="?id=<?= $idUser ?>&page=<?= 1 ?>"><?= 1 ?></a>
            <?php if($page < 9): ?>
                ...
            <?php endif ?>
        <?php endif ?>
        <?php if($page >= 9): ?>
            <a href="?id=<?= $idUser ?>&page=<?= ceil($page / 3) ?>"><?= ceil($page / 3) ?></a>
            <a href="?id=<?= $idUser ?>&page=<?= ceil($page * 2 / 3) ?>"><?= ceil($page * 2 / 3) ?></a>
            ...
        <?php endif ?>
        <?php if($page >= 3): ?>
            <?php for($i = $page - 2; $i < $page; $i++): ?>
                <a href="?id=<?= $idUser ?>&page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if($nbPages > 1): ?>
            <a class="current" href="?id=<?= $idUser ?>&page=<?= $page ?>"><?= $page ?></a>
        <?php endif ?>
        <?php if($page <= $nbPages - 2): ?>
            <?php for($i = $page + 1; $i <= $page + 2; $i++): ?>
                <a href="?id=<?= $idUser ?>&page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) >= 3): ?>
            ...
            <a href="?id=<?= $idUser ?>&page=<?= ceil(1/3 * ($nbPages - $page) + $page) ?>"><?= ceil(1/3 * ($nbPages - $page) + $page) ?></a>
            <a href="?id=<?= $idUser ?>&page=<?= ceil(2/3 * ($nbPages - $page) + $page) ?>"><?= ceil(2/3 * ($nbPages - $page) + $page) ?></a>
        <?php endif ?>
        <?php if($page < $nbPages): ?>
            <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) < 3): ?>
                ...
            <?php endif ?>
            <a href="?id=<?= $idUser ?>&page=<?= $nbPages ?>"><?= $nbPages ?></a>
            <a class="stream" href="?id=<?= $idUser ?>&page=<?= $page + 1 ?>">Suivant <i class="fas fa-chevron-right"></i></a>
        <?php endif ?>
    </nav>
    <?php if($nbPictures > 0): ?>
        <noscript>
            <p>
                Pour accéder à cette fonctionnalité, vous devez activer JavaScript. Voici les
                <a href="https://www.enable-javascript.com/fr/">instructions pour activer JavaScript dans votre navigateur Web</a>.
            </p>
        </noscript>
        <?php for($i = ($page - 1) * $limit + 1; ($i <= $page * $limit) && ($i <= $nbPictures); $i++): ?>
            <figure class="drawings">
                <figcaption>
                    <p class="titledrawing"><?= stristr($contentDirPicture[$i - 1], '.', true) ?></p>
                </figcaption>
                <figure>
                    <embed class="rig" src="<?= $dirPicture . $contentDirPicture[$i - 1] ?>">
                    <figcaption>
                        <?php $comment = @file_get_contents($dirComment . stristr($contentDirPicture[$i - 1], '.', true) . '.txt') ?>
                        <p class="commentdrawing"><?= $comment ?></p>
                    </figcaption>
                </figure>
            </figure>
        <?php endfor ?>
    <?php else: ?>
        <p id="nothing">Cet utilisateur n'a pas de dessin public.</p>
    <?php endif ?>
    <nav class="counter">
        <?php if($page > 1): ?>
            <a class="stream" href="?id=<?= $idUser ?>&page=<?= $page - 1 ?>"><i class="fas fa-chevron-left"></i> Précédent</a>
            <a href="?id=<?= $idUser ?>&page=<?= 1 ?>"><?= 1 ?></a>
            <?php if($page < 9): ?>
                ...
            <?php endif ?>
        <?php endif ?>
        <?php if($page >= 9): ?>
            <a href="?id=<?= $idUser ?>&page=<?= ceil($page / 3) ?>"><?= ceil($page / 3) ?></a>
            <a href="?id=<?= $idUser ?>&page=<?= ceil($page * 2 / 3) ?>"><?= ceil($page * 2 / 3) ?></a>
            ...
        <?php endif ?>
        <?php if($page >= 3): ?>
            <?php for($i = $page - 2; $i < $page; $i++): ?>
                <a href="?id=<?= $idUser ?>&page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if($nbPages > 1): ?>
            <a class="current" href="?id=<?= $idUser ?>&page=<?= $page ?>"><?= $page ?></a>
        <?php endif ?>
        <?php if($page <= $nbPages - 2): ?>
            <?php for($i = $page + 1; $i <= $page + 2; $i++): ?>
                <a href="?id=<?= $idUser ?>&page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) >= 3): ?>
            ...
            <a href="?id=<?= $idUser ?>&page=<?= ceil(1/3 * ($nbPages - $page) + $page) ?>"><?= ceil(1/3 * ($nbPages - $page) + $page) ?></a>
            <a href="?id=<?= $idUser ?>&page=<?= ceil(2/3 * ($nbPages - $page) + $page) ?>"><?= ceil(2/3 * ($nbPages - $page) + $page) ?></a>
        <?php endif ?>
        <?php if($page < $nbPages): ?>
            <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) < 3): ?>
                ...
            <?php endif ?>
            <a href="?id=<?= $idUser ?>&page=<?= $nbPages ?>"><?= $nbPages ?></a>
            <a class="stream" href="?id=<?= $idUser ?>&page=<?= $page + 1 ?>">Suivant <i class="fas fa-chevron-right"></i></a>
        <?php endif ?>
    </nav>
</main>