<main>
    <h1>Forum</h1>
    <h2>Tous mes sujets</h2>
    <nav class="counter">
        <?php if($page > 1): ?>
            <a class="stream" href="?page=<?= $page - 1 ?>"><i class="fas fa-chevron-left"></i> Précédent</a>
            <a href="?page=<?= 1 ?>"><?= 1 ?></a>
            <?php if($page < 9): ?>
                ...
            <?php endif ?>
        <?php endif ?>
        <?php if($page >= 9): ?>
            <a href="?page=<?= ceil($page / 3) ?>"><?= ceil($page / 3) ?></a>
            <a href="?page=<?= ceil($page * 2 / 3) ?>"><?= ceil($page * 2 / 3) ?></a>
            ...
        <?php endif ?>
        <?php if($page >= 3): ?>
            <?php for($i = $page - 2; $i < $page; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if($nbPages > 1): ?>
            <a class="current" href="?page=<?= $page ?>"><?= $page ?></a>
        <?php endif ?>
        <?php if($page <= $nbPages - 2): ?>
            <?php for($i = $page + 1; $i <= $page + 2; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) >= 3): ?>
            ...
            <a href="?page=<?= ceil(1/3 * ($nbPages - $page) + $page) ?>"><?= ceil(1/3 * ($nbPages - $page) + $page) ?></a>
            <a href="?page=<?= ceil(2/3 * ($nbPages - $page) + $page) ?>"><?= ceil(2/3 * ($nbPages - $page) + $page) ?></a>
        <?php endif ?>
        <?php if($page < $nbPages): ?>
            <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) < 3): ?>
                ...
            <?php endif ?>
            <a href="?page=<?= $nbPages ?>"><?= $nbPages ?></a>
            <a class="stream" href="?page=<?= $page + 1 ?>">Suivant <i class="fas fa-chevron-right"></i></a>
        <?php endif ?>
    </nav>
    <?php if($nbMySubjects > 0): ?>
        <table id="mysubjects">
            <thead>
                <tr>
                    <th>Sujet</th>
                    <th>Créé le</th>
                    <th>Nombre de messages</th>
                    <th>Dernier message</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($mySubjects as $mySubject): ?>
                <tr>
                    <td><a href="messages.php?idSubject=<?= $mySubject['id_subject'] ?>"><?= $mySubject['title'] ?></a></td>
                    <td> <?= $mySubject['created_at'] ?></td>
                    <td>
                        <?php $nbMessages = $db->queryOne('SELECT COUNT(*) AS nb FROM messages WHERE id_subject = ?', [$mySubject['id_subject']]) ?>
                        <?= $nbMessages['nb'] ?>
                    </td>
                    <td>
                        <?php $idLastMessage = $db->queryOne('SELECT MAX(id_message) AS id_last FROM messages WHERE id_subject = ?', [$mySubject['id_subject']]) ?>
                        <?php $datetimeLastMessage = $db->queryOne('SELECT DATE_FORMAT(created_at, \'%d/%m/%y %Hh%i\') AS created_at FROM messages WHERE id_message = ? AND id_subject = ?', [$idLastMessage['id_last'], $mySubject['id_subject']]) ?>
                        <?= $datetimeLastMessage['created_at'] ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php else: ?>
        <p id="nothing">
            Vous n'avez pas créé de sujet.
            <a href="creatingsubject.php"><button>Créer un sujet</button></a>
        </p>
    <?php endif ?>
    <nav class="counter">
        <?php if($page > 1): ?>
            <a class="stream" href="?page=<?= $page - 1 ?>"><i class="fas fa-chevron-left"></i> Précédent</a>
            <a href="?page=<?= 1 ?>"><?= 1 ?></a>
            <?php if($page < 9): ?>
                ...
            <?php endif ?>
        <?php endif ?>
        <?php if($page >= 9): ?>
            <a href="?page=<?= ceil($page / 3) ?>"><?= ceil($page / 3) ?></a>
            <a href="?page=<?= ceil($page * 2 / 3) ?>"><?= ceil($page * 2 / 3) ?></a>
            ...
        <?php endif ?>
        <?php if($page >= 3): ?>
            <?php for($i = $page - 2; $i < $page; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if($nbPages > 1): ?>
            <a class="current" href="?page=<?= $page ?>"><?= $page ?></a>
        <?php endif ?>
        <?php if($page <= $nbPages - 2): ?>
            <?php for($i = $page + 1; $i <= $page + 2; $i++): ?>
                <a href="?page=<?= $i ?>"><?= $i ?></a>
            <?php endfor ?>
        <?php endif ?>
        <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) >= 3): ?>
            ...
            <a href="?page=<?= ceil(1/3 * ($nbPages - $page) + $page) ?>"><?= ceil(1/3 * ($nbPages - $page) + $page) ?></a>
            <a href="?page=<?= ceil(2/3 * ($nbPages - $page) + $page) ?>"><?= ceil(2/3 * ($nbPages - $page) + $page) ?></a>
        <?php endif ?>
        <?php if($page < $nbPages): ?>
            <?php if(ceil((1/3 * ($nbPages - $page) + $page) - $page) < 3): ?>
                ...
            <?php endif ?>
            <a href="?page=<?= $nbPages ?>"><?= $nbPages ?></a>
            <a class="stream" href="?page=<?= $page + 1 ?>">Suivant <i class="fas fa-chevron-right"></i></a>
        <?php endif ?>
    </nav>
</main>